
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    test.App\Repository\CategoryRepository: '@App\Repository\CategoryRepository'
    test.App\Repository\ContributionRepository: '@App\Repository\ContributionRepository'
    test.App\Repository\ContributorRoleRepository: '@App\Repository\ContributorRoleRepository'
    test.App\Repository\EpisodeRepository: '@App\Repository\EpisodeRepository'
    test.App\Repository\InstitutionRepository: '@App\Repository\InstitutionRepository'
    test.App\Repository\LanguageRepository: '@App\Repository\LanguageRepository'
    test.App\Repository\PersonRepository: '@App\Repository\PersonRepository'
    test.App\Repository\PodcastRepository: '@App\Repository\PodcastRepository'
    test.App\Repository\PublisherRepository: '@App\Repository\PublisherRepository'
    test.App\Repository\SeasonRepository: '@App\Repository\SeasonRepository'
